version: "3.8"

#==============================================================================#
#                        DOCKER PARA APP POTO                                  #
#==============================================================================#

services:
#-----------------------------------------------------------------------#
  mariadb:
    image: mariadb:latest
    container_name: poto-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: poto_db
      MYSQL_USER: poto_user
      MYSQL_PASSWORD: poto_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

#-----------------------------------------------------------------------#
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: poto-phpmyadmin
    restart: always
    environment: 
      PMA_HOST: mariadb 
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      - mariadb

#-----------------------------------------------------------------------#
  python-app:
    build: 
      context: ../src/
      dockerfile: Dockerfile
    container_name: poto-python
    restart: always
    volumes:
      - ../src:/app
    working_dir: /app
    command: python3 app.py
    depends_on:
      - mariadb
    ports: 
      - "5000:5000"

#-----------------------------------------------------------------------#
volumes:
  mariadb_data:
